apiVersion: v1
kind: PersistentVolume 
metadata: 
  name: test1-pv 
spec: 
  capacity: 
    storage: 1Gi
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /test1
    server: 211.183.3.99 
    readOnly: false
