apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: deploy-nginx 
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: my-nginx-pods-label 
  template: 
    metadata: 
      name: my-nginx-pod 
      labels: 
        app: my-nginx-pods-label
    spec: 
      containers: 
      - name: nginx 
        image: tonyhan18/testweb:green
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-nodeport 
spec: 
  ports: 
  - name: nginx-port 
    targetPort: 80 
    port: 80 
  selector: 
    app: my-nginx-pods-label
  type: LoadBalancer
