apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: deploy-nginx 
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: my-nginx-pods-label 
  template: 
    metadata: 
      name: my-nginx-pod 
      labels: 
        app: my-nginx-pods-label
    spec: 
      containers: 
      - name: nginx 
        image: tonyhan18/testweb:green
        ports: 
        - containerPort: 80
