apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod 
  namespace: default 
spec:
  containers: 
  - name: my-nginx-ctn
    image: brian24/testeb:green 
    ports:
    - containerPort: 80 
      protocol: TCP
