apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gildong-pvc-nfs-dynamic
spec:
  storageClassName: gildong-nfs-storageclass # SAME NAME AS THE STORAGECLASS
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 1Gi
