apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata: 
  name: user1rolebinding 
  namespace: default 
subjects:
- kind: ServiceAccount 
  name: user1 
roleRef: 
  kind: Role 
  name: user1role 
  apiGroup: rbac.authorization.k8s.io
