apiVersion: v1
kind: PersistentVolume 
metadata: 
  name: ebs-pv 
spec: 
  capacity: 
    storage: 1Gi 
  accessModes: 
    - ReadWriteOnce 
  awsElasticBlockStore: 
    fsType: ext4 
    volumeID: vol-05c9293b63cb3952b
